import com.vooazdomain.Vooaz.modelsData.datas.TourismGuide

object TouristGuides {
    val guides = listOf(
        TourismGuide(
            tourismGuideId = 1,
            name = "Carlos Ferreira",
            specialty = "Guia de Turismo Cultural",
            country = "Brasil",
            state = "São Paulo",
            city = "São Paulo",
            neighborhood = "Interlagos",
            languages = listOf("Português", "Inglês"),
            rating = 4.8,
            email = "carlos.ferreira@email.com",
            contact = "+5511991234567",
            type = "Autônomo",
            disabilitySpecialty = "Deficiência Visual"
        ),
        TourismGuide(
            tourismGuideId = 2,
            name = "Ana Souza",
            specialty = "Guia de Turismo Natural",
            country = "Brasil",
            state = "São Paulo",
            city = "São Paulo",
            neighborhood = "São Mateus",
            languages = listOf("Português", "Espanhol"),
            rating = 4.6,
            email = "ana.souza@email.com",
            contact = "+5511987654321",
            type = "Vinculado a empresa",
            disabilitySpecialty = "Deficiência Auditiva"
        ),
        TourismGuide(
            tourismGuideId = 3,
            name = "Beatriz Santos",
            specialty = "Guia de Turismo de Acessibilidade",
            country = "Brasil",
            state = "São Paulo",
            city = "São Paulo",
            neighborhood = "Moema",
            languages = listOf("Português"),
            rating = 4.9,
            email = "beatriz.santos@email.com",
            contact = "+5511998765432",
            type = "Autônomo",
            disabilitySpecialty = "Ambas"
        ),
        TourismGuide(
            tourismGuideId = 4,
            name = "Alaide Carvalho Ribeiro",
            specialty = "Guia de Turismo Natural",
            country = "Brasil",
            state = "São Paulo",
            city = "Santos",
            neighborhood = "Bom Retiro",
            languages = listOf("Português", "Inglês"),
            rating = 5.0,
            email = "alaideribe409@gmail.com",
            contact = "+5511909458763",
            type = "Autônomo",
            disabilitySpecialty = "Deficiência Visual"
        ),
        TourismGuide(
            tourismGuideId = 5,
            name = "Marina Guimarães",
            specialty = "Guia de Turismo de Acessibilidade",
            country = "Brasil",
            state = "São Paulo",
            city = "Ubatuba",
            neighborhood = "Praia Grande",
            languages = listOf("Português"),
            rating = 4.7,
            email = "mariguima2040@gmail.com",
            contact = "+5511970825639",
            type = "Vinculado a empresa",
            disabilitySpecialty = "Deficiência Auditiva"
        ),
        TourismGuide(
            tourismGuideId = 6,
            name = "Priscila Furlan",
            specialty = "Guia de Turismo Cultural",
            country = "Brasil",
            state = "São Paulo",
            city = "Bertioga",
            neighborhood = "Jardim Albatroz",
            languages = listOf("Português", "Inglês"),
            rating = 4.3,
            email = "prifurlan@gmail.com",
            contact = "+5511914896572",
            type = "Vinculado a empresa",
            disabilitySpecialty = "Ambas"
        ),
        TourismGuide(
            tourismGuideId = 7,
            name = "Henrique Costa",
            specialty = "Guia de Turismo Natural",
            country = "Brasil",
            state = "São Paulo",
            city = "São Paulo",
            neighborhood = "Ipiranga",
            languages = listOf("Português", "Espanhol", "Inglês"),
            rating = 4.6,
            email = "henriqeucosta3098@gmail.com",
            contact = "+5511940587632",
            type = "Vinculado a empresa",
            disabilitySpecialty = "Deficiência Auditiva"
        ),
        TourismGuide(
            tourismGuideId = 8,
            name = "Jucelino da Silva",
            specialty = "Guia de Turismo de Acessibilidade",
            country = "Brasil",
            state = "São Paulo",
            city = "São Paulo",
            neighborhood = "Higienópolis",
            languages = listOf("Português"),
            rating = 4.9,
            email = "julelinosilva@gmail.com",
            contact = "+5511978459682",
            type = "Autônomo",
            disabilitySpecialty = "Deficiência Visual"
        ),
        TourismGuide(
            tourismGuideId = 9,
            name = "Guilherme Ferreira da Silva",
            specialty = "Guia de Turismo Cultural",
            country = "Brasil",
            state = "Minas Gerais",
            city = "Ouro Preto",
            neighborhood = "Alto da Cruz",
            languages = listOf("Português"),
            rating = 3.9,
            email = "guilhermefereira2028@gmail.com",
            contact = "+5531946859752",
            type = "Autônomo",
            disabilitySpecialty = "Ambas"
        ),
        TourismGuide(
            tourismGuideId = 10,
            name = "Cristina Ribeiro Paiva",
            specialty = "Guia de Turismo de Acessibilidade",
            country = "Brasil",
            state = "Ceará",
            city = "Jijoca de Jericoacoara",
            neighborhood = "Formosa",
            languages = listOf("Português", "Espanhol", "Inglês"),
            rating = 5.0,
            email = "crisribeiro3039@gmail.com",
            contact = "+5585934576598",
            type = "Vinculado a empresa",
            disabilitySpecialty = "Deficiência Auditiva"
        ),
        TourismGuide(
            tourismGuideId = 11,
            name = "Felipe Barbosa Queiroz",
            specialty = "Guia de Turismo Cultural",
            country = "Itália",
            state = "Vêneto",
            city = "Veneza",
            neighborhood = "San Polo",
            languages = listOf("Português", "Espanhol", "Italiano"),
            rating = 4.5,
            email = "felipebarbosa@gmail.com",
            contact = "+39041.4862378",
            type = "Vinculado a empresa",
            disabilitySpecialty = "Ambas"
        ),
        TourismGuide(
            tourismGuideId = 12,
            name = "Almir Pierogui Alencar",
            specialty = "Guia de Turismo de Acessibilidade",
            country = "Estados Unidos",
            state = "Flórida",
            city = "Orlando",
            neighborhood = "Windermere",
            languages = listOf("Português", "Espanhol", "Inglês"),
            rating = 4.3,
            email = "Almirperre@gmail.com",
            contact = "+1 407 5796412",
            type = "Vinculado a empresa",
            disabilitySpecialty = "Ambas"
        ),
        TourismGuide(
            tourismGuideId = 13,
            name = "Gisele Carvalho Rodrigues",
            specialty = "Guia de Turismo de Acessibilidade",
            country = "Chile",
            state = "Região Metropolitana",
            city = "Santiago",
            neighborhood = "Bellavista",
            languages = listOf("Português", "Espanhol", "Inglês"),
            rating = 4.9,
            email = "gisellecarvalho45@gmail.com",
            contact = "+560225882010",
            type = "Autônomo",
            disabilitySpecialty = "Visual"
        )
    )
}
